### ISSUE TITLE
@InternalCoroutinesAPI usage

### ISSUE THREAD

**Issue by ConorPFarrell** [jillesvangurp/es-kotlin-wrapper-client#10]
This seems like a really useful library, thanks for helping to reduce the boilerplate for Kotlin + Elasticsearch! However, all the @InternalCoroutinesAPI annotations that are required make me a bit wary of using it.

As far as I can tell, none of them are actually necessary, however. I cloned the repo and removed them all, and the Gradle build succeeded - I'm using Kotlin 1.3.50. Am I missing something obvious?

**Comment by jillesvangurp** [comment]
You might be right; I've been meaning to clean this up. I'm in the process of adding some new features and more documentation.

**Comment by ConorPFarrell** [comment]
I've created a PR which removes the annotations if it's helpful to you. Looking forward to the next release!

**Comment by jillesvangurp** [comment]
Awesome, I merged #11 and released a new version. Thanks!
