### ISSUE TITLE
Could not find es-kotlin-wrapper-client.jar

### ISSUE THREAD

**Issue by jhfsantana** [jillesvangurp/es-kotlin-wrapper-client#14]
hi, i'm trying building my project on production and a have the follow error:

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find es-kotlin-wrapper-client.jar (com.github.jillesvangurp:es-kotlin-wrapper-client:v0.9.4).
     Searched in the following locations:
         https://repository.mulesoft.org/nexus/content/repositories/public/com/github/jillesvangurp/es-kotlin-wrapper-client/v0.9.4/es-kotlin-wrapper-client-v0.9.4.jar

I couldn't find the jar file on :https://repository.mulesoft.org/nexus/content/repositories/public/com/github/jillesvangurp/es-kotlin-wrapper-client/

Last modified on directory:
**v0.9.4/ | Mon Dec 16 22:06:27 UTC 2019**

The pom's file is there but the JAR file isnt
Can you help me?

**Comment by jillesvangurp** [comment]
Several releases around that release failed. Try the latest 1.0-M5, it should be fine and includes an few other nice fixes.
