### ISSUE TITLE
[Async]IndexRepository should support source filtering

### ISSUE THREAD

**Issue by goodhoko** [jillesvangurp/es-kotlin-wrapper-client#23]
Elastic API provides [mechanism for source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-source-filtering).

In kotlin/java this is exposed eg. on `GetRequest`
```kotlin
GetRequest(index).fetchSourceContext(FetchSourceContext(true, included, excluded))
```
or various RequestBuilders eg.
```kotlin
SearchRequestBuilder(...).setFetchSource(included, excluded))
```
There is currently no way to leverage this ability with [Async]IndexRepository. Typical usage of source filtering are indices with fields that are only used for searching but are not needed to populate the corresponding entity in the application. Consider for example a simple index for storing cities and their geospatial polygons to be searchable by the elastic geo queries.
```json
{
  "mappings": {
    "properties": {
      "name": {
        "type": "keyword"
      },
      "geometry": {
        "type": "geo_shape"
      },
    }
  }
}
```
Here the geometry field is a **huge** geo-json describing the city a geospatial polygon. But in the app we are only interested in the name. In such case it makes sense to exclude the `geometry` field from the fetched source to lower transferred data and reduce parsing of the JSON on client side. (JSON keys cannot be skipped.)

I think that in context of IndexRepositories it would make sense to only expose ability to set `FetchSourceContext` per repository not necessarily per request.

**Comment by jillesvangurp** [comment]
Thanks for raising this. I may look at this in the next few weeks; but I'm quite busy doing consultancy currently and a little behind on my ambitions with this project. 

If you feel up to it, feel free to do a PR. I'm thinking that source field in any case should be optional (as well as deserialization of the response). And it's already possible to get the raw search response items. On paper as long as you don't attempt to deserialize, it should just work. 

I have some ongoing work to define a search DSL (see recent commits for this on master). Adding source filtering to that should be fairly straightforward. No need to use the  builders for this.

**Comment by goodhoko** [comment]
I will try to get to this during weekend. Will see. .)
