### ISSUE TITLE
Cannot download recent releases from jitpack

### ISSUE THREAD

**Issue by nadnerb** [jillesvangurp/es-kotlin-wrapper-client#29]
Hi,

The only release I can reference and download in my gradle file is: `1.0-Beta-1-7.5.2` via jitpack.

Thanks

**Comment by nadnerb** [comment]
I haven't used Gradle for many years and only just trying Kotlin. I believe using `api` as opposed to `implementation` solved the issue.

**Comment by jillesvangurp** [comment]
1.0-X-Beta-7-7.8.0 is the current release.
