### ISSUE TITLE
underscore naming convention woes

### ISSUE THREAD

**Issue by smonasco** [jillesvangurp/es-kotlin-wrapper-client#30]
### Use Case

I'm using this library without any of the repository functionality. Our users can create fields for objects on the fly. We are in the middle of an update from ES 1.5 to ES 7.8.

So our solution needs to match field names already in production and of course any new ones. We currently do some massaging of the display name to create some internal name. As part of the upgrade process we will be running their old cluster alongside the new cluster. We'd like to avoid changing the internal name as that would require rebuilding their old cluster which could cause significant downtime.

The problem I am running into is that when creating MatchQuery and RangeQuery objects the library is calling `snakeCaseToUnderscore`. This isn't being applied to field names when I use `HighLevelRestClient.searchAsync`. I love that it's turning that into a Kotlin coroutine thing.

My current workaround is to apply `snakeCaseToUnderscore` before calling `searchAsync`, however, this means I need to map field names coming out back to the original casing. This is impossible to do a full list of the original names which would require a doable but undesirable postgres call/caching and the saving grace that we don't have collisions on case.

Here is an example of a problematic field name `is4K`. `snakeCaseToUnderscore` converts this and `is4k` to `is4k` so without extra context an unmapper can't be sure what the original name was.

### Proposed Solutions

A) I can keep around a full list of our fields, but this may not work for everyone if they allow names to have case collisions.

B) We can add functionality to snakeCaseToUnderscore such that `is4K` -> `is4_k` and `is4k` -> `is4k` (basically add numerics to the look back part of the regex). This won't solve an initial caps problem `Is4k` -> `is4k` . To solve all the cases we will need to not rely on toLowerCase at all since it's the part that makes the return unmappable without state.

C) Make query field name case modification configurable. 

Assuming: that we need the case alteration for other parts of the ES DSL.
 
We could have some global config object with an enum on field casing. The MatchQuery and RangeQuery could pass something back in to MapBackedProperties to indicate the type is field name (inline class?) which would give MapBackedProperties the context to apply different modification semantics than it does to other properties.

Although if my assumption is incorrect it may just be a global config that determines wether or not the modification is applied to the keys.

Let me know what you think @jillesvangurp I'd be happy to help with implementation.

**Comment by jillesvangurp** [comment]
Hi thanks for reaching out. I actually had to work around this myself a few weeks ago and was thinking of changing this as it may be too limiting/opinionated. It's kind of an invasive change to make at this point but it may be necessary to do. 

In any case, I'm planning to do a maintenance release soon to update to 7.9 and I might have a go at addressing this one way or another. I think this is something that needs to be configurable ultimately and probably something that you'd want to sync with json serialization as well.

Upgrading from 1.5 sounds like a massive project. I shut down my last 1.7 cluster only last year.

**Comment by jillesvangurp** [comment]
Duplicates #26

**Comment by jillesvangurp** [comment]
Fixed it; in the end decided to add to leave the choice to the user for field names. The rest of the DSL we have to snake case because that's just how ES works. Again thanks for reporting.

**Comment by smonasco** [comment]
@jillesvangurp you're awesome. 1 day turnaround. Nice!
