### ISSUE TITLE
should i close client manual?

### ISSUE THREAD

**Issue by zzhgithub** [jillesvangurp/es-kotlin-wrapper-client#5]
Hi ，
when i use your project to curd with ES.
i build the client. but when i search something.should i close the client manual?

**Comment by jillesvangurp** [comment]
Sorry did not see your issue until now. 

But yes, RestHighLevelClient implements `Closable` so you should close it, eventually. If you are using this in a web application, you would do this on shut down and reuse the instance. So don't close it in between requests.

**Comment by zzhgithub** [comment]
thx ,
by the way.  cause of not close the client, my web application Memory overflow。but i fix it.Although this previous story，thank you for confirming my guess at the time.
good luck!
