### ISSUE TITLE
How to keep the original field information?

### ISSUE THREAD

**Issue by fuuqiu** [jillesvangurp/es-kotlin-wrapper-client#8]
for example @timestamp    _type    ; and Field is at the root node

**Comment by jillesvangurp** [comment]
You get back the original `SearchResponse` from the underlying Java client so check their documentation. So you can either use the Hits they return or the mapped hits the kotlin Wrapper adds, or both. `_type` has been deprecated in ES 7. I don't think `@timestamp` is a top level field; it's just a normal field.

**Comment by fuuqiu** [comment]
kibana index patterns _source.age ,in kotlin code Is there a convenient way to create an index for the dao attribute?

**Comment by jillesvangurp** [comment]
Schema generation is currently not part of the client. Elasticsearch has a schema less indexing that you can use that should work fine with whatever domain model you have. But at some point you'll want to narrow that down. A good starting point then is the autogenerated schema for ES.
